### ISSUE TITLE
Accommodating substantial EggTimer changes

### ISSUE THREAD

**Issue by rousskov** [dgmltn/EggTimer#1]
We have implemented many substantial changes and enhancements on top of your EggTimer bot. They currently live on a work-in-progress [branch](https://github.com/measurement-factory/EggTimer/blob/SQUID-330-initial-merge-bot-impl-2/) and are summarized in its [README](https://github.com/measurement-factory/EggTimer/blob/SQUID-330-initial-merge-bot-impl-2/README.md). We could polish the branch and submit a pull request, but since our changes both alter the nature of EggTimer (from a simple bot to an eventually comprehensive merging/CI tool) _and_ will require serious ongoing maintenance, it feels like we should discuss the best way to proceed first.

I have sent a couple of emails to @dgmltn address found in git commit logs but got no response. If you would like to discuss this, please respond. If we do not hear from you, then, to minimize potential conflicts and user confusion, our default action would be to rename the bot.

**Comment by dgmltn** [comment]
Very nice! I'm not sure how to proceed though, because I don't have the time for "serious ongoing maintenance" here :-/

**Comment by rousskov** [comment]
I see the following three reasonable options, in no particular order:

* Joint venture: Merge Factory changes (after your review and any necessary corrections) into your code. Create a GitHub "organization" to maintain the official EggTimer repository, with you and Factory as members of that organization. Maintain EggTimer long-term together.

* Divide and conquer: Rename Factory bot to avoid any confusion with its EggTimer origin (our documentation will still gratefully acknowledge EggTimer as the bootstrapping base for the project, of course). Refactor Factory repository so that it is no longer a fork of EggTimer. You and
the Factory team go their separate ways after that, without any coordination or collaboration.

* Switcheroo: In the unlikely event you are not going to work on EggTimer anymore, but still want to preserve its name and a tighter association with your original code, Factory can become an official
EggTimer repository owner.

FWIW, the "Joint venture" option sounds attractive to me, but I think its overheads/complexities only make sense if your ideas of what EggTimer should become are closely aligned with the Squid Project needs (and you want to contribute). While it is tempting to create a "universal merge bot" that many projects can then adopt, I suspect that doing so is rather difficult, and neither Factory nor you have the
resources to build something like that -- even Mozilla could not quite pull it off, with Mozilla teams struggling with several outdated/disjoint merge bots (AFAIK). Instead, each party probably
should focus on their specific needs, as the other two options outline.

Needless to say, you may see a better option not summarized above.

I can suggest the following decision making algorithm:

* If you plan to actively work on EggTimer and like our changes, then consider the "Joint venture" option. Perhaps increased brain power will outweigh the overheads and direction conflicts.
* Otherwise, if you would prefer others to take your project to the next step while preserving its original EggTimer name, then vote for the "Switcheroo" option.
* Otherwise, "Divide and conquer" may be the best way forward.

How do you think we should proceed?

**Comment by rousskov** [comment]
We timed out and went with the "Divide and Conquer" approach, creating a new [Anubis](https://github.com/measurement-factory/anubis) bot. As of https://github.com/measurement-factory/anubis/commit/ba70b3a434079041c1e95f86038d3abcaa14777e, EggTimer is mentioned in legal [NOTICES](https://github.com/measurement-factory/anubis/blob/master/NOTICE) and in the Background/Origins section of [README](https://github.com/measurement-factory/anubis/blob/master/README.md).

I am closing this issue to get out of your hair, but please let me know if you would like any changes in how EggTimer is acknowledged within Anubis. For example, we would love to mention you by name in README (the current text just thanks `the EggTimer author`). And thank you again for EggTimer!
